### ISSUE TITLE
Direction not allowed as member of GeneralFrame

### ISSUE THREAD

**Issue by metienne** [nick-knowles/NeTEx-XML#16]
Direction object is not allowed in a GeneralFrame <members> tag; <Route> can refers it by <DirectionRef> element but adding a Direction in <members> tag causes Xerces error : 

cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.netex.org.uk/netex":Direction}'. One of '{"http://www.netex.org.uk/netex":GeneralFrameMember, "http://www.netex.org.uk/netex":DataManagedObject, "http://www.netex.org.uk/netex":Entity_Entity}' is expected.

**Comment by nick-knowles** [comment]
This is a bug because the substitutiongroup  (TypeOfValue) was missing so it was nt picke dup.

**Comment by nick-knowles** [comment]
Fixed 2018
