### ISSUE TITLE
Bugs in xsd:selector where xpath expression does not namespace in the child element 

### ISSUE THREAD

**Issue by skinkie** [nick-knowles/NeTEx-XML#17]
```xsd
<xsd:selector xpath=".//netex:ResponsibilityRoleAssignment/ResponsibleAreaRef"/>
```
This must be changed to:
```xsd
<xsd:selector xpath=".//netex:ResponsibilityRoleAssignment/netex:ResponsibleAreaRef"/>
```
This will affect **all** files with xsd:selector's for key-ref validation.

**Comment by nick-knowles** [comment]
Thansk - have fixed subparts without namespaces in  v1.06

**Comment by skinkie** [comment]
In true github spirit, which commit do you refer to?

**Comment by seime** [comment]
@nick-knowles it would be great and much more efficient for all parties if we could use the git and github concepts available
