### ISSUE TITLE
Typo in RailSubmodeEnumeration

### ISSUE THREAD

**Issue by mariankassovic** [nick-knowles/NeTEx-XML#18]
There is typo in RailSubmodeEnumeration [netex_sub_mode_version-v1.0.xsd](https://raw.githubusercontent.com/nick-knowles/NeTEx-XML/1.04beta/schema/xsd/netex_framework/netex_reusableComponents/netex_submode_version-v1.0.xsd)

`<xsd:enumeration value="intermational"/>`
should be inter**n**ational instead

**Comment by Aurige** [comment]
I just found another one in   [netex_facilityUic_version-v1.0.xsd]( NeTEx-XML/schema/1.03/xsd/netex_framework/netex_reusableComponents/netex_facilityUic_version-v1.0.xsd )
`<xsd:enumeration value="AllI Inclusive Price"/>`
"AllI" should be just "All"
