### ISSUE TITLE
SupplementToFareProductRef references fare product PRICE id instead of fare product id

### ISSUE THREAD

**Issue by mariankassovic** [nick-knowles/NeTEx-XML#19]
Hallo!
   I guess that it is a mistake in netex_fareProduct_version-v1.0.xsd (v1.04b) where SUPPLEMENT PRODUCT should be able to reference FARE PRODUCT to which it is a supplement (according to documentation) by means of SupplementToFareProductRef. However, in scheme it refers to FareProductPriceIdType, and not to the FareProductIdType (see bellow) as I would  expect.

    <xsd:group name="SupplementProductGroup">
		<xsd:annotation>
			<xsd:documentation>Elements for a PREASSIGNED FARE PRODUCT.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="SupplementToFareProductRef" type="FareProductPriceIdType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>FARE PRODUCT to which this is a sublement.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:group>

**Comment by nick-knowles** [comment]
Fixed 2018
