### ISSUE TITLE
Please fix your publication

### ISSUE THREAD

**Issue by skinkie** [nick-knowles/NeTEx-XML#2]
netex_service/netex_dataObjectRequest_service-v1.0.xsd:4: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Skipping import of schema located at 'siri/siri_requests-v2.0.xsd' for the namespace 'http://www.siri.org.uk/siri', since this namespace was already imported with the schema located at 'siri_utility/siri_participant-v2.0.xsd'.
Schemas parser error : element decl. '{http://www.netex.org.uk/netex}DataObjectRequest', attribute 'substitutionGroup': The QName value '{http://www.siri.org.uk/siri}AbstractFunctionalServiceRequest' does not resolve to a(n) element declaration.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:87: element complexType: Schemas parser error : complex type 'DataObjectRequestStructure', attribute 'base': The QName value '{http://www.siri.org.uk/siri}AbstractFunctionalServiceRequestStructure' does not resolve to a(n) simple type definition.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:95: element element: Schemas parser error : Element '{http://www.w3.org/2001/XMLSchema}element', attribute 'ref': The QName value '{http://www.siri.org.uk/siri}Extensions' does not resolve to a(n) element declaration.
Schemas parser error : element decl. '{http://www.netex.org.uk/netex}DataObjectSubscriptionRequest', attribute 'substitutionGroup': The QName value '{http://www.siri.org.uk/siri}AbstractFunctionalServiceSubscriptionRequest' does not resolve to a(n) element declaration.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:129: element complexType: Schemas parser error : complex type 'DataObjectSubscriptionStructure', attribute 'base': The QName value '{http://www.siri.org.uk/siri}AbstractSubscriptionStructure' does not resolve to a(n) simple type definition.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:142: element element: Schemas parser error : Element '{http://www.w3.org/2001/XMLSchema}element', attribute 'ref': The QName value '{http://www.siri.org.uk/siri}Extensions' does not resolve to a(n) element declaration.
Schemas parser error : element decl. '{http://www.netex.org.uk/netex}DataObjectDelivery', attribute 'substitutionGroup': The QName value '{http://www.siri.org.uk/siri}AbstractFunctionalServiceDelivery' does not resolve to a(n) element declaration.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:167: element complexType: Schemas parser error : complex type 'DataObjectDeliveryStructure', attribute 'base': The QName value '{http://www.siri.org.uk/siri}AbstractServiceDeliveryStructure' does not resolve to a(n) simple type definition.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:184: element element: Schemas parser error : element decl. '{http://www.netex.org.uk/netex}DataObjectCapabilitiesRequest', attribute 'type': The QName value '{http://www.siri.org.uk/siri}ServiceCapabilitiesRequestStructure' does not resolve to a(n) type definition.
Schemas parser error : element decl. '{http://www.netex.org.uk/netex}DataObjectCapabilitiesRequest', attribute 'substitutionGroup': The QName value '{http://www.siri.org.uk/siri}AbstractFunctionalServiceCapabilitiesRequest' does not resolve to a(n) element declaration.
Schemas parser error : element decl. '{http://www.netex.org.uk/netex}DataObjectCapabilitiesResponse', attribute 'substitutionGroup': The QName value '{http://www.siri.org.uk/siri}AbstractFunctionalServiceCapabilitiesResponse' does not resolve to a(n) element declaration.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:195: element complexType: Schemas parser error : complex type 'DataObjectCapabilitiesResponseStructure', attribute 'base': The QName value '{http://www.siri.org.uk/siri}AbstractServiceCapabilitiesResponseStructure' does not resolve to a(n) simple type definition.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:206: element attribute: Schemas parser error : attribute decl. 'version', attribute 'type': The QName value '{http://www.siri.org.uk/siri}VersionString' does not resolve to a(n) simple type definition.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:220: element complexType: Schemas parser error : complex type 'DataObjectServiceCapabilitiesStructure', attribute 'base': The QName value '{http://www.siri.org.uk/siri}AbstractCapabilitiesStructure' does not resolve to a(n) simple type definition.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:279: element complexType: Schemas parser error : complex type 'DataObjectCapabilityRequestPolicyStructure', attribute 'base': The QName value '{http://www.siri.org.uk/siri}CapabilityRequestPolicyStructure' does not resolve to a(n) simple type definition.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:317: element complexType: Schemas parser error : complex type 'DataObjectServicePermissionStructure', attribute 'base': The QName value '{http://www.siri.org.uk/siri}AbsoluteBearingType' does not resolve to a(n) simple type definition.
WXS schema NeTEx_publication.xsd failed to compile

And see here how: https://github.com/StichtingOpenGeo/NeTEx/commits/v1.01

**Comment by nick-knowles** [comment]
The version 1.03 released in December  ago should have fixed the issue.

**Comment by skinkie** [comment]
Will test it shortly.

**Comment by skinkie** [comment]
Still applies:

```
NeTEx-XML/schema/1.03/xsd $ xmllint --schema NeTEx_publication.xsd /home/skinkie/Downloads/Proefbestand\ 2.xml.stefan
netex_service/netex_dataObjectRequest_service-v1.0.xsd:4: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Skipping import of schema located at 'siri/siri_requests-v2.0.xsd' for the namespace 'http://www.siri.org.uk/siri', since this namespace was already imported with the schema located at 'siri_utility/siri_participant-v2.0.xsd'.
Schemas parser error : element decl. '{http://www.netex.org.uk/netex}DataObjectRequest', attribute 'substitutionGroup': The QName value '{http://www.siri.org.uk/siri}AbstractFunctionalServiceRequest' does not resolve to a(n) element declaration.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:87: element complexType: Schemas parser error : complex type 'DataObjectRequestStructure', attribute 'base': The QName value '{http://www.siri.org.uk/siri}AbstractFunctionalServiceRequestStructure' does not resolve to a(n) simple type definition.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:95: element element: Schemas parser error : Element '{http://www.w3.org/2001/XMLSchema}element', attribute 'ref': The QName value '{http://www.siri.org.uk/siri}Extensions' does not resolve to a(n) element declaration.
Schemas parser error : element decl. '{http://www.netex.org.uk/netex}DataObjectSubscriptionRequest', attribute 'substitutionGroup': The QName value '{http://www.siri.org.uk/siri}AbstractFunctionalServiceSubscriptionRequest' does not resolve to a(n) element declaration.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:129: element complexType: Schemas parser error : complex type 'DataObjectSubscriptionStructure', attribute 'base': The QName value '{http://www.siri.org.uk/siri}AbstractSubscriptionStructure' does not resolve to a(n) simple type definition.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:142: element element: Schemas parser error : Element '{http://www.w3.org/2001/XMLSchema}element', attribute 'ref': The QName value '{http://www.siri.org.uk/siri}Extensions' does not resolve to a(n) element declaration.
Schemas parser error : element decl. '{http://www.netex.org.uk/netex}DataObjectDelivery', attribute 'substitutionGroup': The QName value '{http://www.siri.org.uk/siri}AbstractFunctionalServiceDelivery' does not resolve to a(n) element declaration.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:167: element complexType: Schemas parser error : complex type 'DataObjectDeliveryStructure', attribute 'base': The QName value '{http://www.siri.org.uk/siri}AbstractServiceDeliveryStructure' does not resolve to a(n) simple type definition.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:184: element element: Schemas parser error : element decl. '{http://www.netex.org.uk/netex}DataObjectCapabilitiesRequest', attribute 'type': The QName value '{http://www.siri.org.uk/siri}ServiceCapabilitiesRequestStructure' does not resolve to a(n) type definition.
Schemas parser error : element decl. '{http://www.netex.org.uk/netex}DataObjectCapabilitiesRequest', attribute 'substitutionGroup': The QName value '{http://www.siri.org.uk/siri}AbstractFunctionalServiceCapabilitiesRequest' does not resolve to a(n) element declaration.
Schemas parser error : element decl. '{http://www.netex.org.uk/netex}DataObjectCapabilitiesResponse', attribute 'substitutionGroup': The QName value '{http://www.siri.org.uk/siri}AbstractFunctionalServiceCapabilitiesResponse' does not resolve to a(n) element declaration.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:195: element complexType: Schemas parser error : complex type 'DataObjectCapabilitiesResponseStructure', attribute 'base': The QName value '{http://www.siri.org.uk/siri}AbstractServiceCapabilitiesResponseStructure' does not resolve to a(n) simple type definition.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:206: element attribute: Schemas parser error : attribute decl. 'version', attribute 'type': The QName value '{http://www.siri.org.uk/siri}VersionString' does not resolve to a(n) simple type definition.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:220: element complexType: Schemas parser error : complex type 'DataObjectServiceCapabilitiesStructure', attribute 'base': The QName value '{http://www.siri.org.uk/siri}AbstractCapabilitiesStructure' does not resolve to a(n) simple type definition.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:279: element complexType: Schemas parser error : complex type 'DataObjectCapabilityRequestPolicyStructure', attribute 'base': The QName value '{http://www.siri.org.uk/siri}CapabilityRequestPolicyStructure' does not resolve to a(n) simple type definition.
netex_service/netex_dataObjectRequest_service-v1.0.xsd:317: element complexType: Schemas parser error : complex type 'DataObjectServicePermissionStructure', attribute 'base': The QName value '{http://www.siri.org.uk/siri}AbsoluteBearingType' does not resolve to a(n) simple type definition.
WXS schema NeTEx_publication.xsd failed to compile
```

**Comment by jllamothe** [comment]
Get the same problem when trying to validate my xml with a xsd validator. Any update ?

**Comment by skinkie** [comment]
@jllamothe there are some forks that should work.

**Comment by laurentg** [comment]
Stumbled upon the same issues trying to compile xsds with xjc (version 2.2.8-b130911.1802 bundled with java 1.8.0_151):

```
[ERROR] src-resolve: Cannot resolve the name 'siri:AbstractFunctionalServiceRequest' to a(n) 'element declaration' component.
  line 82 of file:[...]/xsd/1.03/xsd/netex_service/netex_dataObjectRequest_service-v1.0.xsd
```

And many other errors of the same type. Any updates?

@skinkie Which working forks are your reffering to?

**Comment by skinkie** [comment]
@laurentg please use https://github.com/NeTEx-CEN/NeTEx

**Comment by laurentg** [comment]
@skinkie Thanks, will try! But what is the *official* repo then? The [NeTEx home page](http://netex-cen.eu/?page_id=14) refers this repo.
