### ISSUE TITLE
Version/StartDate Version/EndDate as xs:dateTime. Why?

### ISSUE THREAD

**Issue by skinkie** [nick-knowles/NeTEx-XML#3]
What is the design reason for Version/StartDate Version/EndDate being xs:dateTime?

``` xml
<StartDate>2013-01-01T00:00:00Z</StartDate>
<EndDate>2013-03-31T00:00:00Z</EndDate>
```

https://github.com/nick-knowles/NeTEx-XML/blob/master/schema/1.03/xsd/netex_framework/netex_responsibility/netex_version_version-v1.0.xsd#L149

While other parts of the standard have defined StartDate/EndDate and FromDate/ToDate as xs:date.

https://github.com/nick-knowles/NeTEx-XML/blob/master/schema/1.03/xsd/netex_framework/netex_reusableComponents/netex_serviceCalendar_version-v1.0.xsd#L188

The latter is something I would like to see uniformly applied.

**Comment by nick-knowles** [comment]
It  is xsd:dateTime as it is a timestamp - a version may start or stop at a point within a day so this is the correct data type. 
Agree it wouldl have been more correct to call it StartDateTime/ EndDateTime but was kept consistent with Transmodel (it is one of the few attributes specified in the original conceptual model) 

Other correctly named  uses of date are semantically just dates
