### ISSUE TITLE
Is ServiceJourney specific AccessibilityAssessment supported?

### ISSUE THREAD

**Issue by skinkie** [nick-knowles/NeTEx-XML#4]
An AccessibilityAssessment can be added as property of a Line. Is it possible to apply this property at ServiceJourney (and therefore vehicle) level?

**Comment by nick-knowles** [comment]
Should probably be a property of VehicleType ; each ServiceJourney can have a Vehicle type.   Could suggest as future enhancement.

**Comment by skinkie** [comment]
Could you reference in the XSD where the VehiceType is referenced in ServiceJourney, because we can only find it in vehicleService as part of Block.

**Comment by nick-knowles** [comment]
Journey can have assessment
