### ISSUE TITLE
Supporting Icons/Graphics within Presentation

### ISSUE THREAD

**Issue by skinkie** [nick-knowles/NeTEx-XML#5]
Several operators use custom graphics specific to a line/direction. The Presentation object allows Color like properties. We would like to find an extension to support Icons. Either by base64 encoding or an URI refering to an external source.

**Comment by nick-knowles** [comment]
One or more InfoLink tags  can be used be used to associated URls with a presentation 
As something of a hack these could be used to link a icon with the line. .
As a future enhancement if we allowed a use defined attribute on user link eg  usage='LineIcon' rhia could be incormporated into NeTEx

Each LINE also allows an 'ALternativePresentation' to be specified - this could be used  for the reverse 
direction  for the LINE.
