### ISSUE TITLE
Part 3 Fares: what is the relationship from a SalesPackage to a (commercial) Price?

### ISSUE THREAD

**Issue by skinkie** [nick-knowles/NeTEx-XML#8]
I notice that the examples of tap_tsi contain a huge set of SalesPackages. But none of them actually show what the fare is to acquire this SalesPackage (discount) itself. I would expect something like a FareProductPrice.

Is this the correct route?
FareTable > pricesFor > SalesPackage which has cells with Amount in it.

**Comment by Aurige** [comment]
Nick has a much better knowledge of the rail's fare than I do... He is currently in US and will probably provide more details once back (mid June), but here are some fist inputs:
- The SalesPackage is different from the FareProductPrice: the FareProductPrice just gives you the rights you purchase, but may even not have a price. The SalesPackage (typically a single ticket or a set of 10 tickets giving with a small discount) usually have a price
- for rails, you may end up with a price which is not predefined (i.e. yield manage fare which is only defined at ordering time)
- And yes, the SalesPackage is a priceable object, and therefore can have a price: see SalesPackagePrice that is referencing the SalesPackage through a SalesPackageRef, or "prices" inside the SalesPackage itself, or the PricingService that is reference by the SalesPackage and that gives you access to the service or organisation that can give you the current price.
